-------------------------------------------------------------------------
-- Single file for enemy blueprint list; keeps other files short
-------------------------------------------------------------------------

local enemy_blueprints = {
	"units/air/baxmoth_drone",
	"units/ground/arachnoid_sentinel_base",
	"units/ground/artigian",
	"units/ground/baxmoth",
	"units/ground/bomogan",
	"units/ground/brabit",
	"units/ground/bradron",
	"units/ground/canceroth",
	"units/ground/canceroth_child_ultra",
	"units/ground/carnicinth",
	"units/ground/crawlog",
	"units/ground/drexolian",
	"units/ground/drillgor",
	"units/ground/flurian",
	"units/ground/fungor",
	"units/ground/geotrupex",
	"units/ground/gnerot",
	"units/ground/granan",
	"units/ground/gulgor",
	"units/ground/hedroner",
	"units/ground/invigor",
	"units/ground/jurvine",
	"units/ground/kafferroceros_ultra",
	"units/ground/kermon",
	"units/ground/krocoon",
	"units/ground/lesigian",
	"units/ground/magmoth",
	"units/ground/moltug",
	"units/ground/morirot",
	"units/ground/mushbit",
	"units/ground/necrodon",
	"units/ground/nerilian",
	"units/ground/nurglax",
	"units/ground/octabit",
	"units/ground/phirian",
	"units/ground/plutrodon",
	"units/ground/poogret",
	"units/ground/shegret",
	"units/ground/stickrid",
	"units/ground/stregaros",
	"units/ground/sulphorit",
	"units/ground/viremoth_child",
	"units/ground/wingmite",
	"units/ground/zorant",
	"units/ground/canoptrix_base",
}

return enemy_blueprints
